[package]
name = "brickui"
version = "0.1.0"
description = "Build your Windows UI brick by brick!"
authors = ["GitGinocchio"]
edition = "2024"

exclude = [
    "src-tauri/target/**",
    "src-tauri/gen/**"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "brickui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = 3 # Prioritizes small binary size (`"s"`). Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.

[dev-dependencies]
cargo-release = "0.25.20"

[build-dependencies]
tauri-build = { version = "2.5.1", features = [ "codegen" ] }

[dependencies]
tauri = { version = "2.9.2", features = [
    "protocol-asset",
    "unstable",
    "tray-icon",
    "image-png"
] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-single-instance = "2.3.6"
tauri-plugin-dialog = "2.4.2"
tauri-plugin-opener = "2.5.2"
tauri-plugin-fs = { version = "2.4.4", features = ["watch"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
schemars = "1.1.0"

windows = { version = "0.61.1", features = [
    "Win32_Foundation",

    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_WindowsProgramming",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_System_Com",

    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell_Common",
    "Win32_UI_Accessibility",
    "Win32_UI_Input",
    "Win32_UI_Shell",

    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",

    "Win32_Devices_Bluetooth",
    "Win32_Devices_Enumeration",
    "Win32_Devices",
] }
winreg = "0.55.0"
uuid = { version = "1.18.0", features = [ "v4"] }
image = "0.25.6"
chrono = "0.4.41"
base64 = "0.22.1"
fs_extra = "1.3.0"
crossbeam = "0.8.4"
sha2 = "0.10.9"
lnk = "0.6.3"
zip = "6.0.0"
anyhow = "1.0.100"
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = [ "fs", "time" ] }
futures = "0.3.31"
tauri-plugin-blec = "0.8.1"
btleplug = { version = "0.11.8", features = [ "serde" ] }
tauri-plugin-shell = "2"
tauri-plugin-http = "2"
