[workspace]
publish = false
git_only = true
repo_url = "https://github.com/BrickUIApp/BrickUIApp"
pr_branch_prefix = "release-plz-"
pr_name = "chore(release): {{ package }} v{{ version }}"
pr_labels = ["release"]
release_commits = "^(feat|fix|refactor):"
dependencies_update = true

[[package]]
name = "brickui" 
changelog_path = "CHANGELOG.md"
changelog_config = "cliff.toml"